# https://taskfile.dev

version: "3"

dotnev: [".env"]

tasks:
  init:
    cmds:
      - npm install

  act:
    cmds:
      - act

  flow-build:
    dir: flow
    cmd: docker build -t flow .

  flow-sh:
    dir: flow
    deps:
      - flow-build
    cmd: docker run -it --rm -v .:/app flow /bin/bash

  flow-sh-exec:
    dir: flow
    deps:
      - flow-build
    cmd: docker run --rm -v .:/app -v /var/run/kawaflow.sock:/var/run/kawaflow.sock flow /bin/bash -c "{{.CLI_ARGS}}"

  flow-lint:
    cmds:
      - task: flow-sh-exec
        vars:
          CLI_ARGS: uv run ruff check .
      # - task: flow-sh-exec
      #   vars:
      #     CLI_ARGS: uv run ty check

  flow-lint-fix:
    cmds:
      - task: flow-sh-exec
        vars:
          CLI_ARGS: uv run ruff format
      - task: flow-sh-exec
        vars:
          CLI_ARGS: uv run ruff check --fix .

  flow-test:
    cmds:
      - task: flow-sh-exec
        vars:
          CLI_ARGS: KAWAFLOW_SOCKET_PATH=/tmp/kawaflow.sock PYTHONPATH=/app uv run pytest

  flow-manager-build:
    dir: flow-manager
    cmds:
      - docker build -t flow-manager .

  flow-manager-sh:
    dir: flow-manager
    deps:
      - flow-manager-build
    cmd: docker run -it --rm -v .:/app flow-manager /bin/bash

  flow-manager-sh-exec:
    dir: flow-manager
    deps:
      - flow-build
    cmd: docker run --rm -v .:/app flow-manager /bin/bash -c "{{.CLI_ARGS}}"

  flow-manager-lint:
    cmds:
      - task: flow-manager-sh-exec
        vars:
          CLI_ARGS: uv run ruff check .
      # - task: flow-sh-exec
      #   vars:
      #     CLI_ARGS: uv run ty check

  flow-manager-lint-fix:
    cmds:
      - task: flow-manager-sh-exec
        vars:
          CLI_ARGS: uv run ruff format
      - task: flow-manager-sh-exec
        vars:
          CLI_ARGS: uv run ruff check --fix .

  flow-manager-test:
    cmds:
      - task: flow-manager-sh-exec
        vars:
          CLI_ARGS: PYTHONPATH=/app uv run pytest

  build:
    cmds:
      - task: flow-build
      - task: flow-manager-build

  test:
    cmds:
      - task: flow-test
      - task: flow-manager-test

  lint:
    cmds:
      - task: flow-lint
      - task: flow-manager-lint

  lint-fix:
    cmds:
      - task: flow-lint-fix
      - task: flow-manager-lint-fix

  repomix:
    cmd: npx repomix

  gemini:
    cmds:
      - npx gemini
