# https://taskfile.dev

version: "3"

dotenv: [".env"]

includes:
  docs:
    taskfile: ./docs/Taskfile.yml
    dir: ./docs
  flow:
    taskfile: ./flow/Taskfile.yml
    dir: ./flow
  flow-manager:
    taskfile: ./flow-manager/Taskfile.yml
    dir: ./flow-manager

tasks:
  init:
    desc: Initialize the project
    cmds:
      - npm install

  repomix:
    desc: Run repomix code analysis
    cmd: npx repomix

  gemini:
    desc: Run Google Gemini CLI
    cmds:
      - npx gemini

  act:
    desc: Run GitHub Actions locally
    cmds:
      - act

  build:
    desc: Build all services
    cmds:
      - task: docs:build
      - task: flow:build
      - task: flow-manager:build

  test:
    desc: Run all tests
    cmds:
      - task: flow:test
      - task: flow-manager:test

  lint:
    desc: Run all linting checks
    cmds:
      - task: flow:lint
      - task: flow-manager:lint

  lint-fix:
    desc: Fix all linting issues
    cmds:
      - task: flow:lint-fix
      - task: flow-manager:lint-fix
