# https://taskfile.dev

version: "3"

dotenv: [".env"]

includes:
  docs:
    taskfile: ./docs/Taskfile.yml
    dir: ./docs
  flow:
    taskfile: ./flow/Taskfile.yml
    dir: ./flow
  kawa:
    taskfile: ./kawa/Taskfile.yml
    dir: ./kawa
  flow-manager:
    taskfile: ./flow-manager/Taskfile.yml
    dir: ./flow-manager
  ui:
    taskfile: ./ui/Taskfile.yml
    dir: ./ui

tasks:
  init:
    desc: Initialize the project
    cmds:
      - npm install

  repomix:
    desc: Run repomix code analysis
    cmd: npx -y repomix

  gemini:
    desc: Run Google Gemini CLI
    cmds:
      - npx -y gemini

  act:
    desc: Run GitHub Actions locally
    cmds:
      - act

  test:
    desc: Run all tests
    cmds:
      - task: flow:test
      - task: kawa:test
      # - task: flow-manager:test
      - task: ui:test

  lint:
    desc: Run all linting checks
    cmds:
      - task: kawa:lint
      # - task: flow-manager:lint

  lint-fix:
    desc: Fix all linting issues
    cmds:
      - task: kawa:lint-fix
      # - task: flow-manager:lint-fix

  compose:
    internal: true
    cmd: docker compose -f compose.yml {{ .CLI_ARGS }}

  compose:build:
    aliases: [build]
    cmds:
      - task: compose
        vars:
          CLI_ARGS: build

  compose:up:
    aliases: [up, start]
    cmds:
      - task: compose
        vars:
          CLI_ARGS: up -d

  compose:down:
    aliases: [down, stop]
    cmds:
      - task: compose
        vars:
          CLI_ARGS: down

  compose:restart:
    aliases: [restart]
    cmds:
      - task: compose
        vars:
          CLI_ARGS: restart

  compose:rebuild:
    aliases: [rebuild]
    cmds:
      - task: compose:down
      - task: compose:build
      - task: compose:up

  compose:logs:
    desc: Show logs
    cmds:
      - task: compose
        vars:
          CLI_ARGS: logs -f {{ .CLI_ARGS }}
