# https://taskfile.dev

version: "3"

dotenv: [".env"]

includes:
  npm:
    taskfile: ./npm.Taskfile.yml
    dir: .
  docs:
    taskfile: ./docs/Taskfile.yml
    dir: ./docs
  flow:
    taskfile: ./flow/Taskfile.yml
    dir: ./flow
  flow-manager:
    taskfile: ./flow-manager/Taskfile.yml
    dir: ./flow-manager
  kawa:
    taskfile: ./kawa/Taskfile.yml
    dir: ./kawa

tasks:
  init:
    desc: Initialize the project
    cmds:
      - task: npm:init

  repomix:
    cmds:
      - task: npm:repomix

  gemini:
    cmds:
      - task: npm:gemini

  act:
    desc: Run GitHub Actions locally
    cmds:
      - act

  build:
    desc: Build all services
    cmds:
      - task: docs:build
      - task: flow:build
      - task: flow-manager:build
      - task: kawa:build

  test:
    desc: Run all tests
    cmds:
      - task: flow:test
      - task: flow-manager:test
      - task: kawa:test

  lint:
    desc: Run all linting checks
    cmds:
      - task: flow-manager:lint
      - task: kawa:lint

  lint-fix:
    desc: Fix all linting issues
    cmds:
      - task: flow-manager:lint-fix
      - task: kawa:lint-fix
