# https://taskfile.dev

version: "3"

dotenv: [".env"]

includes:
  docs:
    taskfile: ./docs/Taskfile.yml
    dir: ./docs
  flow:
    taskfile: ./flow/Taskfile.yml
    dir: ./flow
  kawa:
    taskfile: ./kawa/Taskfile.yml
    dir: ./kawa
  flow-manager:
    taskfile: ./flow-manager/Taskfile.yml
    dir: ./flow-manager

tasks:
  init:
    desc: Initialize the project
    cmds:
      - npm install

  repomix:
    desc: Run repomix code analysis
    cmd: npx -y repomix

  gemini:
    desc: Run Google Gemini CLI
    cmds:
      - npx -y gemini

  act:
    desc: Run GitHub Actions locally
    cmds:
      - act

  build:
    desc: Build all services
    parallel: true
    cmds:
      - task: kawa:build
      - task: flow:build
      - task: flow-manager:build

  test:
    desc: Run all tests
    cmds:
      - task: flow:test
      - task: kawa:test
      # - task: flow-manager:test

  lint:
    desc: Run all linting checks
    cmds:
      - task: kawa:lint
      # - task: flow-manager:lint

  lint-fix:
    desc: Fix all linting issues
    cmds:
      - task: kawa:lint-fix
      # - task: flow-manager:lint-fix
