# https://taskfile.dev

version: "3"

includes:
  private: ./Taskfile.private.yml

tasks:
  act:
    cmds:
      - act

  template-docker-build:
    dir: "{{ .ROOT_DIR }}/flow-template"
    cmds:
      - docker build -t flow-template .

  template-docker-sh:
    dir: "{{ .ROOT_DIR }}/flow-template"
    cmds:
      - docker run -it --rm -v /var/run/kawaflow.sock:/var/run/kawaflow.sock flow-template /bin/bash

  template-lint:
    dir: "{{ .ROOT_DIR }}/flow-template"
    cmds:
      - uv run ruff check .
      - uv run ty check .

  lint:
    cmds:
      - task template-lint
  
  repomix:
    cmd: npx repomix
