[project]
name = "flow-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.12.3",
    "ty>=0.0.1a14",
    "pytest>=8.0.0",
]
