version: "3"

tasks:
  build:
    desc: Build the flow service Docker image
    dir: ../
    cmd: docker build -t flow -f flow/Dockerfile .

  test:
    cmd: docker run --rm -it flow /bin/bash -c 'uv run python -c "from kawa import registry; print(registry.dump()); from kawa.serve import serve; print(serve)"'
