version: "3"

tasks:
  build:
    desc: Build the flow service Docker image
    cmd: docker build -t flow .

  sh-exec:
    desc: Execute a command in the flow container
    cmd: docker run --rm -v .:/app -v /var/run/kawaflow.sock:/var/run/kawaflow.sock flow /bin/bash -c "{{.CLI_ARGS}}"
    internal: true

  ruff:
    desc: Run ruff linting
    cmds:
      - task: sh-exec
        vars:
          CLI_ARGS: uv run ruff check .

  ty:
    desc: Run type checking
    cmds:
      - task: sh-exec
        vars:
          CLI_ARGS: uv run ty check

  lint:
    desc: Run all linting checks
    cmds:
      - task: ruff
      - task: ty

  ruff-fix:
    desc: Fix ruff linting issues
    cmds:
      - task: sh-exec
        vars:
          CLI_ARGS: uv run ruff format
      - task: sh-exec
        vars:
          CLI_ARGS: uv run ruff check --fix .

  lint-fix:
    desc: Fix all linting issues
    cmds:
      - task: ruff-fix

  test:
    desc: Run flow service tests
    cmds:
      - task: sh-exec
        vars:
          CLI_ARGS: SOCKET_PATH=/tmp/kawaflow.sock PYTHONPATH=/app uv run pytest {{.CLI_ARGS}}
