version: "3"

tasks:
  build:
    desc: Build the flow service Docker image
    dir: ../
    cmd: docker build -t flow -f flow/Dockerfile .

  sh:
    cmd: docker run --rm -it -v .:/app flow /bin/bash

  sh-exec:
    cmd: docker run --rm -v .:/app flow /bin/bash -c '{{.CLI_ARGS}}'
    internal: true

  test:
    cmds:
      - task: sh-exec
        vars:
          CLI_ARGS: uv run --with=/tmp/kawa test.py
