# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: build
      - task: up
      - task: migrate
      - task: test
      - task: down

  compose:
    internal: true
    cmd: docker compose --project-directory . -f e2e/compose.yml {{ .CLI_ARGS }}

  build:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: --profile build --profile test build

  up:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: up -d

  down:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: down

  migrate:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: exec -T ui-app php artisan migrate --force

  test:
    desc: Run E2E tests with HTML report
    cmds:
      - task: compose
        vars:
          CLI_ARGS: --profile test run --rm -T e2e uv run python /app/scripts/run_e2e_with_report.py

  pytest:
    desc: Run pytest in e2e container (no report)
    cmds:
      - task: compose
        vars:
          CLI_ARGS: --profile test run --rm -T e2e uv run pytest {{.CLI_ARGS}}

  pytest:k:
    desc: Run pytest with -k expression (no report)
    cmds:
      - task: compose
        vars:
          CLI_ARGS: --profile test run --rm -T e2e uv run pytest -k {{.CLI_ARGS}} -vv

  pytest:node:
    desc: Run a single test/node id (no report)
    cmds:
      - task: compose
        vars:
          CLI_ARGS: --profile test run --rm -T e2e uv run pytest {{.CLI_ARGS}} -vv

  pytest:lf:
    desc: Re-run last failed tests (no report)
    cmds:
      - task: compose
        vars:
          CLI_ARGS: --profile test run --rm -T e2e uv run pytest --lf -vv
