site_name: Kawaflow Documentation
site_author: Kawaflow Team

docs_dir: /docs

repo_name: noartem/kawaflow
repo_url: https://github.com/noartem/kawaflow

# Navigation
nav:
  - Home: index.md
  - Flow Manager:
      - Home: flow-manager/index.md
      - API Reference: flow-manager/api_reference.md
      - Usage Guide: flow-manager/usage_guide.md
      - Error Handling: flow-manager/error_handling.md
      - Deployment Guide: flow-manager/deployment_guide.md

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - tables
  - toc:
      permalink: true

copyright: Copyright &copy; 2025 Kawaflow Team
