version: "3"

tasks:
  build:
    desc: Build the documentation Docker image
    cmds:
      - docker build -t docs .
      - docker run --rm -v ./docs:/docs docs mkdocs build

  serve:
    desc: Serve the documentation locally
    cmds:
      - docker run --rm -p 8000:8000 -v ./docs:/docs docs

  export-pdf:
    desc: Export documentation as PDF
    cmds:
      - docker run --rm -v ./docs:/docs docs sh -c "pip install mkdocs-pdf-export-plugin && mkdocs build"
