version: "3"

tasks:
  compose:
    internal: true
    dir: ../
    cmd: docker compose -f compose.yml {{ .CLI_ARGS }}

  test:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: run --rm ui-app php artisan test {{.CLI_ARGS}}

  migrate:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: run --rm ui-app php artisan migrate {{.CLI_ARGS}}

  sh:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: exec ui-app bash

  tinker:
    aliases: [ ti ]
    cmds:
      - task: compose
        vars:
          CLI_ARGS: exec ui-app php artisan tinker

  db:reset:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: run --rm ui-app php artisan migrate:fresh --seed {{.CLI_ARGS}}

  schedule:run:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: run --rm ui-app php artisan schedule:run {{.CLI_ARGS}}
