version: "3"

tasks:
  compose:
    internal: true
    dir: ../
    cmd: docker compose -f compose.yml {{ .CLI_ARGS }}

  copy-vendor:
    cmds:
#      - task: compose
#        vars:
#          CLI_ARGS: cp ui-app:/var/www/html/vendor ./ui/vendor
      - task: compose
        vars:
          CLI_ARGS: cp ui-app:/var/www/html/node_modules ./ui/node_modules

  test:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: run --rm ui-app php artisan test {{.CLI_ARGS}}

  migrate:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: exec ui-app php artisan migrate {{.CLI_ARGS}}

  sh:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: exec ui-app bash

  sh-execute:
    aliases: [ shc ]
    cmds:
      - task: compose
        vars:
          CLI_ARGS: exec ui-app bash -c "{{.CLI_ARGS}}"

  tinker:
    aliases: [ ti ]
    cmds:
      - task: compose
        vars:
          CLI_ARGS: exec ui-app php artisan tinker

  db:reset:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: exec ui-app php artisan migrate:fresh --seed {{.CLI_ARGS}}

  db:local-seed:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: exec ui-app php artisan db:seed --class="Database\\Seeders\\LocalDemoSeeder" {{.CLI_ARGS}}

  schedule:run:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: exec ui-app php artisan schedule:run {{.CLI_ARGS}}
