version: "3"

tasks:
  compose:
    internal: true
    dir: ../
    cmd: docker compose -f compose.yml {{ .CLI_ARGS }}

  exec:
    internal: true
    dir: ../
    cmd: docker compose -f compose.yml exec -w /var/www/html ui-app {{ .CLI_ARGS }}

  copy-vendor:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: cp ui-app:/var/www/html/vendor ./ui/vendor
      - task: compose
        vars:
          CLI_ARGS: cp ui-app:/var/www/html/node_modules ./ui/node_modules

  test:
    cmds:
      - task: compose
        vars:
          CLI_ARGS: run --rm ui-app php artisan test {{.CLI_ARGS}}

  migrate:
    cmds:
      - task: exec
        vars:
          CLI_ARGS: php artisan migrate {{.CLI_ARGS}}

  sh:
    cmds:
      - task: exec
        vars:
          CLI_ARGS: bash

  sh-execute:
    aliases: [ shc ]
    cmds:
      - task: exec
        vars:
          CLI_ARGS: bash -c "{{.CLI_ARGS}}"

  tinker:
    aliases: [ ti ]
    cmds:
      - task: exec
        vars:
          CLI_ARGS: php artisan tinker

  boost:mcp:
    aliases: [ ti ]
    cmds:
      - task: exec
        vars:
          CLI_ARGS: php artisan boost:mcp

  db:reset:
    cmds:
      - task: exec
        vars:
          CLI_ARGS: php artisan migrate:fresh {{.CLI_ARGS}}

  db:local-seed:
    cmds:
      - task: exec
        vars:
          CLI_ARGS: php artisan db:seed --class="Database\\Seeders\\DatabaseSeeder" {{.CLI_ARGS}}

  db:demo-seed:
    cmds:
      - task: exec
        vars:
          CLI_ARGS: php artisan db:seed --class="Database\\Seeders\\LocalDemoSeeder" {{.CLI_ARGS}}

  schedule:run:
    cmds:
      - task: exec
        vars:
          CLI_ARGS: php artisan schedule:run {{.CLI_ARGS}}
