name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-flow-template:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: flow-template

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Check flow-template
        run: |
          uv run ruff check .
          uv run ty check .
